### PR TITLE
actually run tests

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 490dbc9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 490dbc9 with merge 490dbc9...

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0950e37 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0950e37 with merge 0950e37...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/191533929)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit b69140b has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit b69140b with merge b69140b...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/191538949)
Approved by: japaric
Pushing b69140b8a95a142fbeceeb1933becaafe04474bc to master...

**Pull request merged**
