### PR TITLE
Fix nr_from_src.py and add statx system call

### PR DESCRIPTION
**Pull request by Amanieu**
Some architectures were missing statx because the script was broken.

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @Amanieu.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e53e5ef has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e53e5efaaa3bd1b126c969baeadbaff083758d23 with merge 8e280bc0b03243e322a046361630de9fb52e134c...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/297736859?utm_source=github_status&utm_medium=notification)
Approved by: japaric
Pushing 8e280bc0b03243e322a046361630de9fb52e134c to master...

**Comment by japaric** [comment]
v0.2.2 has been published with this change.

**Pull request merged**
