### PR TITLE
linux: test that the return code, in the error case, has the right sign

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 94ea638 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 94ea638 with merge 94ea638...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/191648858)
Approved by: japaric
Pushing 94ea6388e1674a235df841ca5225d400929b2c94 to master...

**Pull request merged**
