### PR TITLE
Fix #13 by taking reference of non-immediate value

### LINKED ISSUE #13: x86 syscall6 gives ICE
I believe that this crate suffers from https://github.com/rust-lang/rust/issues/39098, namely in the x86 syscall6

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks, @tbu-.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c86f386 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c86f386 with merge 77f7fe4...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/204689818)
Approved by: japaric
Pushing 77f7fe4fdcb7800db1d9656ad1f1e5d4d5f1b1a3 to master...

**Pull request merged**
