### PR TITLE
fix syscall2 for linux-aarch64

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit afc4b25 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit afc4b25 with merge afc4b25...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/192021548)
Approved by: japaric
Pushing afc4b25219e006712577ac7fbc6458acc6348fdd to master...

**Pull request merged**
