### PR TITLE
overhaul

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit c028823 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit c028823 with merge c028823...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/191166544)

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit ee65e7a has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit ee65e7a with merge ee65e7a...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/191531924)
Approved by: japaric
Pushing ee65e7a4838ccf30c73b6696e3a9b0fc20a2fb05 to master...

**Pull request merged**
