### PR TITLE
implement syscall5 and syscall6 for mips

### PR DESCRIPTION
**Pull request by japaric**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit e37f1a7 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit e37f1a7 with merge e37f1a7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/194030952)
Approved by: japaric
Pushing e37f1a709b9811f00b527b0db6a91a354e525c47 to master...

**Pull request merged**
