### PR TITLE
Fix `GETRANDOM` constant on x86, mixed up with x86_64

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by tbu-** [comment]
Sorry!

**Comment by japaric** [comment]
No problem, @tbu-. This really should be auto generated to avoid problems with manual copy pasting.

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 8c10006 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 8c10006 with merge 8c10006...

**Comment by tbu-** [comment]
@japaric The problem seemed to be that `getrandom` wasn't supported by these docker images. Is that possible?

**Comment by tbu-** [comment]
(I tried generating it, but it didn't return a number.)

**Comment by japaric** [comment]
> The problem seemed to be that getrandom wasn't supported by these docker images. Is that possible?

Yes, that's possible. IIRC, GETRANDOM was added in Linux 3.17 and you probably used a docker image based on Ubuntu 12.04, which probably has kernel headers older than 3.17, so it was not available in that particular image.

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/198068925)
Approved by: japaric
Pushing 8c10006aa273f06f153aa3ed0ed2cf4662b57939 to master...

**Pull request merged**
