### PR TITLE
mips: set .noat to appease asm! warnings

### PR DESCRIPTION
**Pull request by japaric**
that pop out when compiling with optimizations

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 1117f00 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 1117f00 with merge 1117f00...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/194047399)
Approved by: japaric
Pushing 1117f0019e179c00d4be6f68c1c6ac76c3781e07 to master...

**Pull request merged**
