### PR TITLE
Add `newfstatat` syscall for Linux

### PR DESCRIPTION
**Pull request by tbu-**

### CODE REVIEW

**Comment by japaric** [comment]
@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 896b3d9 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 896b3d9 with merge ee704d7...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/194059294)
Approved by: japaric
Pushing ee704d7f8e807a4a2c90f25b9ca2b2b38b7e5bbc to master...

**Pull request merged**
