### PR TITLE
Fix #12: parse kernel sources to get numbers

### LINKED ISSUE #12: Include constants for new syscalls
In linux HEAD, there are a number of new syscalls (including `copy_file_range`, the one I am interested in), which are not exposed. Please add constants for them:
https://github.com/torvalds/linux/blob/master/include/uapi/asm-generic/unistd.h#L707

### PR DESCRIPTION
**Pull request by FauxFaux**
I wrote some new code to generate the syscall numbers from the kernel sources, based on the ideas in:

 * https://github.com/kmcallister/syscall.rs/issues/8
 * https://github.com/japaric/sc-gen

The commit also updates the tables for Linux 4.10, released a few days ago. The important discrepancies (`git show | egrep '^-' | fgrep -v //`) are:

```
--- a/src/platform/linux-armeabi/nr.rs
-pub const SYNC_FILE_RANGE2: usize = 341;
```
`arm-eabi` declares `sync_file_range2` as `arm_sync_file_range`, under that number. The compatibility name is listed in the table.. could support it?

```
--- a/src/platform/linux-sparc64/nr.rs
-pub const GETRESGID: usize = 111;
-pub const GETRESUID: usize = 109;
-pub const SETRESGID: usize = 110;
-pub const SETRESUID: usize = 108;
```

`sparc64` declares `GETRESGID32` instead, as that number, which sounds about right to me. I didn't try a real sparc machine.

Everything else is additions, or removal of the comments (which this technique doesn't generate).

The tool:
 * Takes a path to the kernel source as an argument.
 * greps the code for all possible syscall names (ew, but ..?)
 * for arches with tables, parses the table and generates the appropriate files
 * for arches without tables:
   * writes a header that would generate something like the table
   * *preprocesses* it with the system `gcc` (with include paths set up properly to use the kernel sources)
   * parses the resulting table

This doesn't require you to have a compiler for the target system, or a compiled kernel for the target system, but does require you to get some defines that the compiler would set right. (ew?)

### CODE REVIEW

**Comment by japaric** [comment]
Wow, this is awesome. Thanks for the PR @FauxFaux!

re: changes in the name of the syscalls. This is fine because the syscalls are still there. These names you have generated appear to be more correct in any case.

The approach seems reasonable to me.

@homunkulus r+

P.S. It just occured to me that we could run this tool "incrementally" from older Linux versions to newer ones (3.1 then 3.2, etc.) to get information about "when" a syscall became available. This information could go in the syscall itself as a doc comment (e.g. `/// Available since Linux 3.2`) or perhaps encoded in some other way (as modules? `mod _3_2` for syscalls that become available in Linux 3.2). This would be useful to projects where supporting older kernels is important.

**Comment by homunkulus** [comment]
:pushpin: Commit 847debb has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 847debb with merge 847debb...

**Comment by homunkulus** [comment]
:sunny: Test successful - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/204255936)
Approved by: japaric
Pushing 847debb0a1de5f756fed124fea671ad722ba99ab to master...

**Comment by tbu-** [comment]
This is awesome, thank you! 🎉

**Pull request merged**
