### PR TITLE
Fix link, Remove Travis CI badge

### PR DESCRIPTION
**Pull request by shimon1024**

### CODE REVIEW

**Comment by japaric** [comment]
Thanks!

@homunkulus r+

**Comment by homunkulus** [comment]
:pushpin: Commit 0276f55 has been approved by `japaric`

**Comment by homunkulus** [comment]
:hourglass: Testing commit 0276f55 with merge 0276f55...

**Comment by homunkulus** [comment]
:broken_heart: Test failed - [status-travis](https://travis-ci.org/japaric/syscall.rs/builds/194497202)

**Comment by japaric** [comment]
@homunkulus retry

**Pull request merged**
